/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package aplikasi_hitung_sederhana;


/**
 *
 * @author Dhanu
 */
public class konversi extends javax.swing.JPanel {

   
        
    /**
     * Creates new form konversi
     */
    public konversi() {
        initComponents();
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtPanjangawal = new javax.swing.JTextField();
        Konversi = new javax.swing.JTextField();
        CBawal = new javax.swing.JComboBox<>();
        CBakhir = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tbkonversi = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(153, 204, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setForeground(new java.awt.Color(153, 153, 255));

        txtPanjangawal.setText("masukan angka");
        txtPanjangawal.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtPanjangawalFocusGained(evt);
            }
        });
        txtPanjangawal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPanjangawalActionPerformed(evt);
            }
        });

        Konversi.setEditable(false);
        Konversi.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                KonversiFocusGained(evt);
            }
        });
        Konversi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KonversiActionPerformed(evt);
            }
        });

        CBawal.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-pilih satuan", "CM", "M", "Inchi", "Kaki", " ", " " }));
        CBawal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBawalActionPerformed(evt);
            }
        });

        CBakhir.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-pilih satuan", "CM", "M", "Inchi", "Kaki", " ", " " }));
        CBakhir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBakhirActionPerformed(evt);
            }
        });

        jLabel1.setText("Hasil Konversi");

        jLabel2.setText("panjang awal");

        tbkonversi.setBackground(new java.awt.Color(255, 204, 204));
        tbkonversi.setText("konversikan");
        tbkonversi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbkonversiActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("konversi panjang");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(Konversi, javax.swing.GroupLayout.DEFAULT_SIZE, 266, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CBakhir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(txtPanjangawal)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CBawal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(tbkonversi)))
                .addContainerGap())
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPanjangawal, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CBawal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Konversi, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CBakhir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addComponent(tbkonversi)
                .addGap(49, 49, 49))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
   double result, Panjangawal;
    String hasil;
     
    private void CBawalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBawalActionPerformed
    Panjangawal =Double.parseDouble(txtPanjangawal.getText());
        String isiCB = (String)CBawal.getSelectedItem();
        switch(isiCB){
            case "CM": 
                if(CBakhir.equals("CM")){ 
                    result =  Panjangawal;
                    hasil =  Double.toString(result);
                }
        }
      
     
    }//GEN-LAST:event_CBawalActionPerformed

    private void KonversiFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_KonversiFocusGained
   // IsiPanjangAwal.Integer.parseInt(Panjangawal.getText());
    }//GEN-LAST:event_KonversiFocusGained

    private void txtPanjangawalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPanjangawalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPanjangawalActionPerformed

    private void KonversiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KonversiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_KonversiActionPerformed

    private void CBakhirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBakhirActionPerformed
      
    }//GEN-LAST:event_CBakhirActionPerformed

    private void tbkonversiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbkonversiActionPerformed
      Panjangawal =Double.parseDouble(txtPanjangawal.getText());
      String isiCBakhir = (String) CBakhir.getSelectedItem();
        String isiCB = (String)CBawal.getSelectedItem();
        switch(isiCB){
            case "CM": 
                if(isiCBakhir.equals("CM")){ 
                    result =  Panjangawal;
                    hasil =  Double.toString(result);
                Konversi.setText(hasil);}
                    else if(isiCBakhir.equals("M")){
                    result = Panjangawal / 100 ;
                 hasil =  Double.toString(result);
                Konversi.setText(hasil);}
                    else if(isiCBakhir.equals("Kaki")){
                    result = Panjangawal / 30.48 ;
                     hasil =  Double.toString(result);
                     Konversi.setText(hasil);}
             
                    else if(isiCBakhir.equals("Inchi")){
                    result = Panjangawal / 2.54 ;
                    hasil =  Double.toString(result);
                    Konversi.setText(hasil);}
                break;
            case "M":
                if(isiCBakhir.equals("M")){ 
                    result =  Panjangawal;
                    hasil =  Double.toString(result);
                Konversi.setText(hasil);}
                    else if(isiCBakhir.equals("CM")){
                    result = Panjangawal * 100 ;
                 hasil =  Double.toString(result);
                Konversi.setText(hasil);}
                    else if(isiCBakhir.equals("Kaki")){
                    result = Panjangawal * 3.28 ;
                     hasil =  Double.toString(result);
                     Konversi.setText(hasil);}
                    else if(isiCBakhir.equals("Inchi")){
                    result = Panjangawal * 39.37 ;
                    hasil =  Double.toString(result);
                    Konversi.setText(hasil);}
                break;
            case "Kaki":
                if(isiCBakhir.equals("Kaki")){ 
                    result =  Panjangawal;
                    hasil =  Double.toString(result);
                Konversi.setText(hasil);}
                    else if(isiCBakhir.equals("CM")){
                    result = Panjangawal * 30.48 ;
                 hasil =  Double.toString(result);
                Konversi.setText(hasil);}
                    else if(isiCBakhir.equals("M")){
                    result = Panjangawal * 0.3048 ;
                     hasil =  Double.toString(result);
                     Konversi.setText(hasil);}
                    else if(isiCBakhir.equals("Inchi")){
                    result = Panjangawal * 12 ;
                    hasil =  Double.toString(result);
                    Konversi.setText(hasil);}
                break;    
            case "Inchi":
                if(isiCBakhir.equals("Inchi")){ 
                    result =  Panjangawal;
                    hasil =  Double.toString(result);
                Konversi.setText(hasil);}
                    else if(isiCBakhir.equals("CM")){
                    result = Panjangawal * 2.54 ;
                 hasil =  Double.toString(result);
                Konversi.setText(hasil);}
                    else if(isiCBakhir.equals("M")){
                    result = Panjangawal * 0.0254;
                     hasil =  Double.toString(result);
                     Konversi.setText(hasil);}
                    else if(isiCBakhir.equals("Kaki")){
                    result = Panjangawal / 12 ;
                    hasil =  Double.toString(result);
                    Konversi.setText(hasil);}
                break;    
     }
       

    }//GEN-LAST:event_tbkonversiActionPerformed

    private void txtPanjangawalFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPanjangawalFocusGained

    }//GEN-LAST:event_txtPanjangawalFocusGained
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CBakhir;
    private javax.swing.JComboBox<String> CBawal;
    private javax.swing.JTextField Konversi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton tbkonversi;
    private javax.swing.JTextField txtPanjangawal;
    // End of variables declaration//GEN-END:variables
}
