/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package aplikasi_hitung_sederhana;

import java.util.LinkedList;
import java.util.Queue;
import javax.swing.JTextField;

/**
 *
 * @author Dhanu
 */
public class mainframe extends javax.swing.JFrame {

    /**
     * Creates new form mainframe
     */
    LinkedList<String> historyqueue= new LinkedList<>();
    StringBuilder sb = new StringBuilder();
private boolean isNegative;
    public mainframe() {
        initComponents();
       angka="";
       konversi konversi = new konversi ();
        jTabbedPane1.addTab("konversi panjang", konversi);
    }
 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollBar1 = new javax.swing.JScrollBar();
        jLabel9 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel5 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtCekInput = new javax.swing.JTextField();
        txtCekOutput = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        btnCek = new javax.swing.JButton();
        btnReset2 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        txtMulai = new javax.swing.JTextField();
        jPanel12 = new javax.swing.JPanel();
        txtSampai = new javax.swing.JTextField();
        jPanel13 = new javax.swing.JPanel();
        txtKelipatan = new javax.swing.JTextField();
        btnCari = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        hasil = new javax.swing.JTextArea();
        jLabel14 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtBil1 = new javax.swing.JTextField();
        txtBil2 = new javax.swing.JTextField();
        btnTambah = new javax.swing.JButton();
        btnkali = new javax.swing.JButton();
        btnkurang = new javax.swing.JButton();
        btnBagi = new javax.swing.JButton();
        btnMod = new javax.swing.JButton();
        txtOut1 = new javax.swing.JTextField();
        reset = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        display = new javax.swing.JTextField();
        tblNeg = new javax.swing.JButton();
        tblPersen = new javax.swing.JButton();
        tblBagi = new javax.swing.JButton();
        tbl7 = new javax.swing.JButton();
        tbl8 = new javax.swing.JButton();
        tbl9 = new javax.swing.JButton();
        tblKali = new javax.swing.JButton();
        tbl4 = new javax.swing.JButton();
        tbl5 = new javax.swing.JButton();
        tbl6 = new javax.swing.JButton();
        tblC = new javax.swing.JButton();
        tblKurang = new javax.swing.JButton();
        tbl1 = new javax.swing.JButton();
        tbl2 = new javax.swing.JButton();
        tbl3 = new javax.swing.JButton();
        tblTambah = new javax.swing.JButton();
        tbl0 = new javax.swing.JButton();
        tblKoma = new javax.swing.JButton();
        tblHasil = new javax.swing.JButton();
        hapushistory = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        history = new javax.swing.JTextArea();
        jLabel13 = new javax.swing.JLabel();

        jLabel9.setText("jLabel9");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("aplikasi bilangan dan perhitungan");

        jTabbedPane1.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));

        jPanel5.setBackground(new java.awt.Color(225, 193, 160));
        jPanel5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Cek Bilangan");
        jPanel5.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 2, 575, -1));

        jLabel6.setText("Masukan Bilangan");
        jPanel5.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 39, -1, -1));

        txtCekInput.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtCekInputFocusGained(evt);
            }
        });
        txtCekInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCekInputActionPerformed(evt);
            }
        });
        jPanel5.add(txtCekInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(104, 36, 150, -1));

        txtCekOutput.setEditable(false);
        txtCekOutput.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtCekOutputFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCekOutputFocusLost(evt);
            }
        });
        txtCekOutput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCekOutputActionPerformed(evt);
            }
        });
        jPanel5.add(txtCekOutput, new org.netbeans.lib.awtextra.AbsoluteConstraints(104, 64, 150, -1));

        jLabel7.setText("Output");
        jPanel5.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 67, 96, -1));

        btnCek.setBackground(new java.awt.Color(204, 255, 255));
        btnCek.setText("Cek");
        btnCek.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnCek.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCekActionPerformed(evt);
            }
        });
        jPanel5.add(btnCek, new org.netbeans.lib.awtextra.AbsoluteConstraints(266, 37, 59, -1));

        btnReset2.setBackground(new java.awt.Color(255, 204, 204));
        btnReset2.setText("Reset");
        btnReset2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnReset2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReset2ActionPerformed(evt);
            }
        });
        jPanel5.add(btnReset2, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 104, 76, -1));
        jPanel5.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 160, -1, -1));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar gui/png-transparent-elementary-mathematics-number-mathematical-notation-mathematics-abstraction-stock-photography-science-transformed (1).png"))); // NOI18N
        jPanel5.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, 460, 370));

        jTabbedPane1.addTab("Cek bilangan", jPanel5);

        jPanel7.setBackground(new java.awt.Color(255, 204, 255));
        jPanel7.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jPanel11.setBackground(new java.awt.Color(204, 204, 255));
        jPanel11.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED), "Mulai", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N

        txtMulai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMulaiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtMulai, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtMulai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jPanel12.setBackground(new java.awt.Color(204, 204, 255));
        jPanel12.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED), "Sampai", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N

        txtSampai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSampaiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtSampai, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtSampai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jPanel13.setBackground(new java.awt.Color(204, 204, 255));
        jPanel13.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED), "Kelipatan", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N

        txtKelipatan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtKelipatanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtKelipatan, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtKelipatan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        btnCari.setBackground(new java.awt.Color(204, 255, 255));
        btnCari.setText("Cari");
        btnCari.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCariActionPerformed(evt);
            }
        });

        hasil.setEditable(false);
        hasil.setColumns(20);
        hasil.setRows(5);
        hasil.setToolTipText("");
        jScrollPane1.setViewportView(hasil);

        jLabel14.setBackground(new java.awt.Color(255, 204, 255));
        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar gui/2e065cf5-37b7-4a7d-a795-b82ae4badc86-transformed (1).png"))); // NOI18N

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 438, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCari, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(btnCari)
                        .addGap(14, 14, 14)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(0, 166, Short.MAX_VALUE)
                        .addComponent(jLabel14))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Kelipatan Bilangan", jPanel2);

        jPanel3.setBackground(new java.awt.Color(198, 226, 233));
        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel2.setText("bilangan 1");

        jLabel3.setText("bilangan 2");

        jLabel4.setText("hasil");

        txtBil1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBil1ActionPerformed(evt);
            }
        });

        btnTambah.setBackground(new java.awt.Color(204, 204, 255));
        btnTambah.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnTambah.setText("+");
        btnTambah.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahActionPerformed(evt);
            }
        });

        btnkali.setBackground(new java.awt.Color(204, 204, 255));
        btnkali.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnkali.setText("x");
        btnkali.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnkali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnkaliActionPerformed(evt);
            }
        });

        btnkurang.setBackground(new java.awt.Color(204, 204, 255));
        btnkurang.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnkurang.setText("-");
        btnkurang.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnkurang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnkurangActionPerformed(evt);
            }
        });

        btnBagi.setBackground(new java.awt.Color(204, 204, 255));
        btnBagi.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnBagi.setText(":");
        btnBagi.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnBagi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBagiActionPerformed(evt);
            }
        });

        btnMod.setBackground(new java.awt.Color(204, 204, 255));
        btnMod.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnMod.setText("%");
        btnMod.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnMod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModActionPerformed(evt);
            }
        });

        txtOut1.setEditable(false);
        txtOut1.setBackground(new java.awt.Color(255, 255, 255));
        txtOut1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtOut1ActionPerformed(evt);
            }
        });

        reset.setBackground(new java.awt.Color(255, 153, 153));
        reset.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        reset.setText("reset");
        reset.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetActionPerformed(evt);
            }
        });

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar gui/images--UaguiOLg-transformed.png"))); // NOI18N
        jLabel11.setText("jLabel11");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtBil1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnTambah, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnkurang, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnMod, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtBil2, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnkali, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnBagi, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtOut1)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(reset, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtBil1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnTambah)
                            .addComponent(btnkurang)
                            .addComponent(btnMod))
                        .addGap(9, 9, 9)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtBil2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnkali)
                            .addComponent(btnBagi))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtOut1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(11, 11, 11)
                .addComponent(reset)
                .addContainerGap(116, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("perhitungan (sederhana)", jPanel3);

        jPanel4.setBackground(new java.awt.Color(167, 190, 211));

        jPanel6.setBackground(new java.awt.Color(0, 0, 0));
        jPanel6.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        jPanel6.setForeground(new java.awt.Color(51, 51, 51));

        display.setEditable(false);
        display.setBackground(new java.awt.Color(51, 51, 51));
        display.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        display.setForeground(new java.awt.Color(0, 196, 222));
        display.setText("ini kalkulator ");
        display.setDisabledTextColor(new java.awt.Color(102, 102, 102));
        display.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displayActionPerformed(evt);
            }
        });

        tblNeg.setBackground(new java.awt.Color(204, 204, 204));
        tblNeg.setFont(new java.awt.Font("Kristen ITC", 0, 14)); // NOI18N
        tblNeg.setText("+/-");
        tblNeg.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tblNeg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tblNegActionPerformed(evt);
            }
        });

        tblPersen.setBackground(new java.awt.Color(204, 204, 204));
        tblPersen.setFont(new java.awt.Font("Kristen ITC", 0, 14)); // NOI18N
        tblPersen.setText("%");
        tblPersen.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tblPersen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tblPersenActionPerformed(evt);
            }
        });

        tblBagi.setBackground(new java.awt.Color(204, 204, 204));
        tblBagi.setFont(new java.awt.Font("Kristen ITC", 0, 14)); // NOI18N
        tblBagi.setText(":");
        tblBagi.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tblBagi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tblBagiActionPerformed(evt);
            }
        });

        tbl7.setBackground(new java.awt.Color(204, 204, 204));
        tbl7.setFont(new java.awt.Font("Kristen ITC", 0, 14)); // NOI18N
        tbl7.setText("7");
        tbl7.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tbl7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbl7ActionPerformed(evt);
            }
        });

        tbl8.setBackground(new java.awt.Color(204, 204, 204));
        tbl8.setFont(new java.awt.Font("Kristen ITC", 0, 14)); // NOI18N
        tbl8.setText("8");
        tbl8.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tbl8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbl8ActionPerformed(evt);
            }
        });

        tbl9.setBackground(new java.awt.Color(204, 204, 204));
        tbl9.setFont(new java.awt.Font("Kristen ITC", 0, 14)); // NOI18N
        tbl9.setText("9");
        tbl9.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tbl9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbl9ActionPerformed(evt);
            }
        });

        tblKali.setBackground(new java.awt.Color(204, 204, 204));
        tblKali.setFont(new java.awt.Font("Kristen ITC", 0, 14)); // NOI18N
        tblKali.setText("x");
        tblKali.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tblKali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tblKaliActionPerformed(evt);
            }
        });

        tbl4.setBackground(new java.awt.Color(204, 204, 204));
        tbl4.setFont(new java.awt.Font("Kristen ITC", 0, 14)); // NOI18N
        tbl4.setText("4");
        tbl4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tbl4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbl4ActionPerformed(evt);
            }
        });

        tbl5.setBackground(new java.awt.Color(204, 204, 204));
        tbl5.setFont(new java.awt.Font("Kristen ITC", 0, 14)); // NOI18N
        tbl5.setText("5");
        tbl5.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tbl5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbl5ActionPerformed(evt);
            }
        });

        tbl6.setBackground(new java.awt.Color(204, 204, 204));
        tbl6.setFont(new java.awt.Font("Kristen ITC", 0, 14)); // NOI18N
        tbl6.setText("6");
        tbl6.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tbl6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbl6ActionPerformed(evt);
            }
        });

        tblC.setBackground(new java.awt.Color(204, 204, 204));
        tblC.setFont(new java.awt.Font("Kristen ITC", 0, 14)); // NOI18N
        tblC.setForeground(new java.awt.Color(248, 162, 8));
        tblC.setText("C");
        tblC.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tblC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tblCActionPerformed(evt);
            }
        });

        tblKurang.setBackground(new java.awt.Color(204, 204, 204));
        tblKurang.setFont(new java.awt.Font("Kristen ITC", 0, 14)); // NOI18N
        tblKurang.setText("-");
        tblKurang.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tblKurang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tblKurangActionPerformed(evt);
            }
        });

        tbl1.setBackground(new java.awt.Color(204, 204, 204));
        tbl1.setFont(new java.awt.Font("Kristen ITC", 0, 14)); // NOI18N
        tbl1.setText("1");
        tbl1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tbl1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbl1ActionPerformed(evt);
            }
        });

        tbl2.setBackground(new java.awt.Color(204, 204, 204));
        tbl2.setFont(new java.awt.Font("Kristen ITC", 0, 14)); // NOI18N
        tbl2.setText("2");
        tbl2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tbl2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbl2ActionPerformed(evt);
            }
        });

        tbl3.setBackground(new java.awt.Color(204, 204, 204));
        tbl3.setFont(new java.awt.Font("Kristen ITC", 0, 14)); // NOI18N
        tbl3.setText("3");
        tbl3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tbl3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbl3ActionPerformed(evt);
            }
        });

        tblTambah.setBackground(new java.awt.Color(204, 204, 204));
        tblTambah.setFont(new java.awt.Font("Kristen ITC", 0, 14)); // NOI18N
        tblTambah.setText("+");
        tblTambah.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tblTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tblTambahActionPerformed(evt);
            }
        });

        tbl0.setBackground(new java.awt.Color(204, 204, 204));
        tbl0.setFont(new java.awt.Font("Kristen ITC", 0, 14)); // NOI18N
        tbl0.setText("0");
        tbl0.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tbl0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbl0ActionPerformed(evt);
            }
        });

        tblKoma.setBackground(new java.awt.Color(204, 204, 204));
        tblKoma.setFont(new java.awt.Font("Kristen ITC", 0, 14)); // NOI18N
        tblKoma.setText(",");
        tblKoma.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tblKoma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tblKomaActionPerformed(evt);
            }
        });

        tblHasil.setBackground(new java.awt.Color(204, 204, 204));
        tblHasil.setFont(new java.awt.Font("Kristen ITC", 0, 18)); // NOI18N
        tblHasil.setForeground(new java.awt.Color(0, 156, 147));
        tblHasil.setText("=");
        tblHasil.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tblHasil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tblHasilActionPerformed(evt);
            }
        });

        hapushistory.setBackground(new java.awt.Color(204, 204, 204));
        hapushistory.setFont(new java.awt.Font("Kristen ITC", 0, 12)); // NOI18N
        hapushistory.setForeground(new java.awt.Color(153, 0, 153));
        hapushistory.setText("clear history");
        hapushistory.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        hapushistory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapushistoryActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(display)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(tbl0, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tblKoma, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tblHasil, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel6Layout.createSequentialGroup()
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel6Layout.createSequentialGroup()
                                        .addComponent(tbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(tbl2, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE))
                                    .addGroup(jPanel6Layout.createSequentialGroup()
                                        .addComponent(tbl4, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(tbl5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(jPanel6Layout.createSequentialGroup()
                                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(tblC, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE)
                                            .addComponent(tbl7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(tbl8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(tblNeg, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tblPersen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(tbl9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(tbl6, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE)
                                    .addComponent(tbl3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tblBagi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tblKali, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tblKurang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tblTambah, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(hapushistory, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(display, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tblNeg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tblPersen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tblBagi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tblC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tbl7, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                    .addComponent(tbl8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tbl9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tblKali, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tbl4, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                    .addComponent(tbl5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tbl6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tblKurang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tbl1, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                    .addComponent(tbl2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tbl3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tblTambah, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tbl0, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tblHasil, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tblKoma, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(hapushistory, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("history");

        history.setColumns(20);
        history.setRows(5);
        jScrollPane2.setViewportView(history);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 167, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 173, Short.MAX_VALUE)))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addGap(262, 262, 262))
            .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar gui/png-transparent-mathematics-rational-number-mathematics-text-numerical-digit-cartoon-transformed (1).png"))); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel13)
                .addGap(180, 180, 180))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, 281, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel13)
                .addGap(37, 37, 37))
        );

        jTabbedPane1.addTab("kalkulator", jPanel4);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 528, Short.MAX_VALUE)
                        .addGap(45, 45, 45))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 418, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
 //deklarasi variabel global
    double bil_1 , bil_2 , out_1 , total , angka1 , angka2 ;
    int bil_cek , mulai, sampai, kelipatan , pilih ;
     String angka ;

    private void ambil_bilangan(){
        bil_1 = Integer.parseInt(txtBil1.getText());
      bil_2 = Integer.parseInt(txtBil2.getText());
    }
// perhitungan sederhana
    private void resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetActionPerformed
        txtOut1.setText("");
        txtBil1.setText("") ;
        txtBil2.setText("");
     
    }//GEN-LAST:event_resetActionPerformed

    private void txtOut1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtOut1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtOut1ActionPerformed

    private void btnModActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModActionPerformed
        ambil_bilangan();
        out_1 = bil_1 % bil_2 ;
        txtOut1.setText(String.valueOf(out_1));
    }//GEN-LAST:event_btnModActionPerformed

    private void btnBagiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBagiActionPerformed
        ambil_bilangan();
        out_1 = bil_1 / bil_2 ;
        txtOut1.setText(String.valueOf(out_1));
    }//GEN-LAST:event_btnBagiActionPerformed

    private void btnkurangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnkurangActionPerformed
        ambil_bilangan();
        out_1 = bil_1 - bil_2 ;
        txtOut1.setText(String.valueOf(out_1));
    }//GEN-LAST:event_btnkurangActionPerformed

    private void btnkaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnkaliActionPerformed
        ambil_bilangan();
        out_1 = bil_1 * bil_2 ;
        txtOut1.setText(String.valueOf(out_1));
    }//GEN-LAST:event_btnkaliActionPerformed

    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
        bil_1 = Integer.parseInt(txtBil1.getText());
        bil_2 = Integer.parseInt(txtBil2.getText());
        out_1 = bil_1 + bil_2 ;
        txtOut1.setText(String.valueOf(out_1));
    }//GEN-LAST:event_btnTambahActionPerformed

    private void txtBil1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBil1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBil1ActionPerformed
//cek bilangan
    private void btnReset2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReset2ActionPerformed
        txtCekInput.setText("");
        txtCekOutput.setText("");
    }//GEN-LAST:event_btnReset2ActionPerformed

    private void btnCekActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCekActionPerformed
          bil_cek = Integer.valueOf(txtCekInput.getText());
        if (bil_cek == 0){
            txtCekOutput.setText("Bilangan Nol");
        }
        else if((bil_cek % 2)== 0){
            txtCekOutput.setText("Bilangan Genap");}
        else if ((bil_cek % 2 )==1) {
            txtCekOutput.setText("Bilangan Ganjil");}

    }//GEN-LAST:event_btnCekActionPerformed

    private void txtCekOutputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCekOutputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCekOutputActionPerformed

    private void txtCekInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCekInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCekInputActionPerformed


// kelipatan biilangan
    private void txtMulaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMulaiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMulaiActionPerformed

    private void txtSampaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSampaiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSampaiActionPerformed

    private void txtKelipatanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtKelipatanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtKelipatanActionPerformed

    private void btnCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCariActionPerformed
        mulai = Integer.parseInt(txtMulai.getText());
        sampai = Integer.parseInt(txtSampai.getText());
        kelipatan = Integer.parseInt(txtKelipatan.getText());
        
        hasil.setText("");
        
        for(int i=mulai; i<=sampai; i++){
            if((i % kelipatan )==0){
        hasil.append(String.valueOf(i ) + "\n");
    }//GEN-LAST:event_btnCariActionPerformed
        }
    }
    // kalkulator
    private void tblCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tblCActionPerformed
       display.setText("");
       angka1 = 0.0 ;
       angka2 = 0.0 ;
       total = 0.0 ;
       angka = "" ;
    }//GEN-LAST:event_tblCActionPerformed

    private void tblNegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tblNegActionPerformed
         angka1=Double.parseDouble(angka);
        display.setText("-");
        angka="";
         isNegative = false;
         isNegative = !isNegative;
    }//GEN-LAST:event_tblNegActionPerformed

    private void tblPersenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tblPersenActionPerformed
         angka2 = Double.parseDouble(angka);
        total = angka2/100;
        angka = Double.toString(total);
        display.setText(angka);
        historyqueue.add((angka2)+(" : ")+(100)+(" = ")+(total)+("\n"));
        if (!historyqueue.isEmpty()) {
            String lastElement = null;
               
               
                for (String element : historyqueue) {
                    lastElement = element;
                    }  
                   sb.append(lastElement).append("\n");
                   history.setText(sb.toString());
        }             
    }//GEN-LAST:event_tblPersenActionPerformed
    
    private void tbl6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbl6ActionPerformed
     angka += "6" ;
        display.setText(angka);
    }//GEN-LAST:event_tbl6ActionPerformed

    private void tbl0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbl0ActionPerformed
     angka += "0" ;
        display.setText(angka);
    }//GEN-LAST:event_tbl0ActionPerformed

    private void tblKomaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tblKomaActionPerformed
    angka += "." ;
    display.setText(angka);
    }//GEN-LAST:event_tblKomaActionPerformed

    private void tblHasilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tblHasilActionPerformed
        switch(pilih){
            case 1: 
                angka2 = Double.parseDouble(angka);
                total = angka1 + angka2;
               angka =  Double.toString(total);
               display.setText(angka);
               historyqueue.add((angka1)+("+")+(angka2)+(" = ")+(total)+("\n"));
            
            if (!historyqueue.isEmpty()) {
            String lastElement = null;
               
               
                for (String element : historyqueue) {
                    lastElement = element;
                    }  
                   sb.append(lastElement).append("\n");
                 
        history.setText(sb.toString());
               
            }
               break;

               
               case 2: 
                angka2 = Double.parseDouble(angka);
                total = angka1 - angka2;
               angka =  Double.toString(total);
               display.setText(angka);
                historyqueue.add((angka1)+("-")+(angka2)+(" = ")+(total)+("\n"));
                if (!historyqueue.isEmpty()) {
            String lastElement = null;
               
               
                for (String element : historyqueue) {
                    lastElement = element;
                    }  
                   sb.append(lastElement).append("\n");
                 
        history.setText(sb.toString());
                }
               break;
               case 3: 
                angka2 = Double.parseDouble(angka);
                total = angka1 * angka2;
               angka =  Double.toString(total);
               display.setText(angka);
                 historyqueue.add((angka1)+("x")+(angka2)+(" = ")+(total)+("\n"));
                if (!historyqueue.isEmpty()) {
            String lastElement = null;
               
               
                for (String element : historyqueue) {
                    lastElement = element;
                    }  
                   sb.append(lastElement).append("\n");
                }
                     history.setText(sb.toString());
                   break;
                
               case 4: 
                angka2 = Double.parseDouble(angka);
                total = angka1 / angka2;
               angka =  Double.toString(total);
               display.setText(angka);
                  historyqueue.add((angka1)+(":")+(angka2)+(" = ")+(total)+("\n"));
                if (!historyqueue.isEmpty()) {
            String lastElement = null;
               
               
                for (String element : historyqueue) {
                    lastElement = element;
                    }  
                   sb.append(lastElement).append("\n");
                        history.setText(sb.toString());
                }
               break;

               
               
        }
    }//GEN-LAST:event_tblHasilActionPerformed

    private void tblTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tblTambahActionPerformed
 angka1= Double.parseDouble(angka);
        display.setText("+");
        angka="";
        pilih= 1;
            }//GEN-LAST:event_tblTambahActionPerformed

    private void tbl3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbl3ActionPerformed
       angka += "3";
        display.setText(angka);
    }//GEN-LAST:event_tbl3ActionPerformed

    private void tbl2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbl2ActionPerformed
        angka += "2";
        display.setText(angka);    }//GEN-LAST:event_tbl2ActionPerformed

    private void tbl1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbl1ActionPerformed
       angka += "1";
        display.setText(angka);
    }//GEN-LAST:event_tbl1ActionPerformed

    private void tbl4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbl4ActionPerformed
       angka += "4";
        display.setText(angka);
    }//GEN-LAST:event_tbl4ActionPerformed

    private void tbl5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbl5ActionPerformed
        angka += "5";
        display.setText(angka);
    }//GEN-LAST:event_tbl5ActionPerformed

    private void tbl7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbl7ActionPerformed
        angka += "7";
        display.setText(angka);
    }//GEN-LAST:event_tbl7ActionPerformed

    private void tbl8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbl8ActionPerformed
        angka += "8";
        display.setText(angka);
    }//GEN-LAST:event_tbl8ActionPerformed

    private void tbl9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbl9ActionPerformed
       angka += "9";
        display.setText(angka);
    }//GEN-LAST:event_tbl9ActionPerformed

    private void tblBagiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tblBagiActionPerformed
        angka1=Double.parseDouble(angka);
        display.setText(":");
        angka="";
        pilih=4 ;
    }//GEN-LAST:event_tblBagiActionPerformed

    private void tblKaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tblKaliActionPerformed
        angka1=Double.parseDouble(angka);
        display.setText("x");
        angka="";
        pilih= 3;
    }//GEN-LAST:event_tblKaliActionPerformed

    private void tblKurangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tblKurangActionPerformed
    angka1=Double.parseDouble(angka);
        display.setText("-");
        angka="";
        pilih=2 ;
       }//GEN-LAST:event_tblKurangActionPerformed

    private void displayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_displayActionPerformed

    private void hapushistoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapushistoryActionPerformed
       historyqueue.clear();
       System.out.println("Jumlah elemen dalam LinkedList: " + historyqueue.size());
       sb.setLength(0);
       history.setText("");
    }//GEN-LAST:event_hapushistoryActionPerformed

    private void txtCekOutputFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCekOutputFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCekOutputFocusGained

    private void txtCekOutputFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCekOutputFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCekOutputFocusLost

    private void txtCekInputFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCekInputFocusGained
  
    }//GEN-LAST:event_txtCekInputFocusGained
      //queue queue = new queue(4);
  
    
    






    

    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mainframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mainframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mainframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mainframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
    
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mainframe().setVisible(true);
            }
        });
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBagi;
    private javax.swing.JButton btnCari;
    private javax.swing.JButton btnCek;
    private javax.swing.JButton btnMod;
    private javax.swing.JButton btnReset2;
    private javax.swing.JButton btnTambah;
    private javax.swing.JButton btnkali;
    private javax.swing.JButton btnkurang;
    private javax.swing.JTextField display;
    private javax.swing.JButton hapushistory;
    private javax.swing.JTextArea hasil;
    private javax.swing.JTextArea history;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollBar jScrollBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JButton reset;
    private javax.swing.JButton tbl0;
    private javax.swing.JButton tbl1;
    private javax.swing.JButton tbl2;
    private javax.swing.JButton tbl3;
    private javax.swing.JButton tbl4;
    private javax.swing.JButton tbl5;
    private javax.swing.JButton tbl6;
    private javax.swing.JButton tbl7;
    private javax.swing.JButton tbl8;
    private javax.swing.JButton tbl9;
    private javax.swing.JButton tblBagi;
    private javax.swing.JButton tblC;
    private javax.swing.JButton tblHasil;
    private javax.swing.JButton tblKali;
    private javax.swing.JButton tblKoma;
    private javax.swing.JButton tblKurang;
    private javax.swing.JButton tblNeg;
    private javax.swing.JButton tblPersen;
    private javax.swing.JButton tblTambah;
    private javax.swing.JTextField txtBil1;
    private javax.swing.JTextField txtBil2;
    private javax.swing.JTextField txtCekInput;
    private javax.swing.JTextField txtCekOutput;
    private javax.swing.JTextField txtKelipatan;
    private javax.swing.JTextField txtMulai;
    private javax.swing.JTextField txtOut1;
    private javax.swing.JTextField txtSampai;
    // End of variables declaration//GEN-END:variables
}

